import Foundation

enum CaldwellCatalog {
    static let objects: [DeepSkyObject] = [
        DeepSkyObject(catalog: .caldwell, number: 1, name: nil, type: .openCluster, constellation: "Cep", raHours: 0.7333, decDegrees: 85.2550, magnitude: 8.1),
        DeepSkyObject(catalog: .caldwell, number: 2, name: nil, type: .planetaryNebula, constellation: "Cep", raHours: 0.2211, decDegrees: 72.5211, magnitude: 11.6),
        DeepSkyObject(catalog: .caldwell, number: 3, name: nil, type: .galaxy, constellation: "Dra", raHours: 19.2708, decDegrees: 69.6797, magnitude: 9.9),
        DeepSkyObject(catalog: .caldwell, number: 4, name: "Iris Nebula", type: .nebula, constellation: "Cep", raHours: 21.0178, decDegrees: 68.1631, magnitude: 6.8),
        DeepSkyObject(catalog: .caldwell, number: 5, name: nil, type: .galaxy, constellation: "Cam", raHours: 3.7797, decDegrees: 68.0961, magnitude: 9.2),
        DeepSkyObject(catalog: .caldwell, number: 6, name: "Cat's Eye Nebula", type: .planetaryNebula, constellation: "Dra", raHours: 17.9752, decDegrees: 66.6331, magnitude: 8.1),
        DeepSkyObject(catalog: .caldwell, number: 7, name: nil, type: .galaxy, constellation: "Cam", raHours: 7.6367, decDegrees: 65.6019, magnitude: 8.9),
        DeepSkyObject(catalog: .caldwell, number: 8, name: nil, type: .openCluster, constellation: "Cas", raHours: 1.9767, decDegrees: 63.3000, magnitude: 9.5),
        DeepSkyObject(catalog: .caldwell, number: 9, name: "Cave Nebula", type: .nebula, constellation: "Cep", raHours: 22.9578, decDegrees: 62.6167, magnitude: 7.7),
        DeepSkyObject(catalog: .caldwell, number: 10, name: nil, type: .openCluster, constellation: "Cas", raHours: 1.8033, decDegrees: 61.2333, magnitude: 6.4),
        DeepSkyObject(catalog: .caldwell, number: 11, name: "Bubble Nebula", type: .nebula, constellation: "Cas", raHours: 23.3453, decDegrees: 61.2000, magnitude: 10.0),
        DeepSkyObject(catalog: .caldwell, number: 12, name: "Fireworks Galaxy", type: .galaxy, constellation: "Cyg", raHours: 20.5822, decDegrees: 60.1539, magnitude: 9.6),
        DeepSkyObject(catalog: .caldwell, number: 13, name: "Owl Cluster", type: .openCluster, constellation: "Cas", raHours: 1.3283, decDegrees: 58.2833, magnitude: 6.4),
        DeepSkyObject(catalog: .caldwell, number: 14, name: "Double Cluster", type: .openCluster, constellation: "Per", raHours: 2.3333, decDegrees: 57.1367, magnitude: 4.3),
        DeepSkyObject(catalog: .caldwell, number: 15, name: "Blinking Planetary", type: .planetaryNebula, constellation: "Cyg", raHours: 19.7444, decDegrees: 50.5253, magnitude: 8.8),
        DeepSkyObject(catalog: .caldwell, number: 16, name: nil, type: .openCluster, constellation: "Lac", raHours: 22.2467, decDegrees: 49.8917, magnitude: 6.4),
        DeepSkyObject(catalog: .caldwell, number: 17, name: nil, type: .galaxy, constellation: "Cas", raHours: 0.5497, decDegrees: 48.5081, magnitude: 9.2),
        DeepSkyObject(catalog: .caldwell, number: 18, name: nil, type: .galaxy, constellation: "Cas", raHours: 0.5622, decDegrees: 48.3372, magnitude: 10.1),
        DeepSkyObject(catalog: .caldwell, number: 19, name: "Cocoon Nebula", type: .nebula, constellation: "Cyg", raHours: 21.8878, decDegrees: 47.2667, magnitude: 7.2),
        DeepSkyObject(catalog: .caldwell, number: 20, name: "North America Nebula", type: .nebula, constellation: "Cyg", raHours: 20.9750, decDegrees: 44.3333, magnitude: 4.0),
        DeepSkyObject(catalog: .caldwell, number: 21, name: nil, type: .galaxy, constellation: "CVn", raHours: 12.4472, decDegrees: 43.9683, magnitude: 9.8),
        DeepSkyObject(catalog: .caldwell, number: 22, name: "Blue Snowball", type: .planetaryNebula, constellation: "And", raHours: 23.4272, decDegrees: 42.5461, magnitude: 8.6),
        DeepSkyObject(catalog: .caldwell, number: 23, name: "Silver Sliver Galaxy", type: .galaxy, constellation: "And", raHours: 2.3706, decDegrees: 42.3492, magnitude: 9.9),
        DeepSkyObject(catalog: .caldwell, number: 24, name: nil, type: .galaxy, constellation: "Per", raHours: 3.3319, decDegrees: 41.5117, magnitude: 11.6),
        DeepSkyObject(catalog: .caldwell, number: 25, name: nil, type: .globularCluster, constellation: "Lyn", raHours: 7.6633, decDegrees: 38.8722, magnitude: 10.4),
        DeepSkyObject(catalog: .caldwell, number: 26, name: nil, type: .galaxy, constellation: "CVn", raHours: 12.2789, decDegrees: 37.4436, magnitude: 10.4),
        DeepSkyObject(catalog: .caldwell, number: 27, name: "Crescent Nebula", type: .nebula, constellation: "Cyg", raHours: 20.2003, decDegrees: 38.3550, magnitude: 7.4),
        DeepSkyObject(catalog: .caldwell, number: 28, name: nil, type: .openCluster, constellation: "And", raHours: 1.9767, decDegrees: 37.6833, magnitude: 6.9),
        DeepSkyObject(catalog: .caldwell, number: 29, name: nil, type: .galaxy, constellation: "CVn", raHours: 13.1608, decDegrees: 37.0331, magnitude: 11.5),
        DeepSkyObject(catalog: .caldwell, number: 30, name: nil, type: .galaxy, constellation: "Peg", raHours: 23.3111, decDegrees: 33.9686, magnitude: 10.9),
        DeepSkyObject(catalog: .caldwell, number: 31, name: "Flaming Star Nebula", type: .nebula, constellation: "Aur", raHours: 5.2650, decDegrees: 34.2667, magnitude: 6.0),
        DeepSkyObject(catalog: .caldwell, number: 32, name: "Whale Galaxy", type: .galaxy, constellation: "CVn", raHours: 12.6650, decDegrees: 32.5586, magnitude: 9.8),
        DeepSkyObject(catalog: .caldwell, number: 33, name: "Eastern Veil Nebula", type: .supernovaRemnant, constellation: "Cyg", raHours: 20.9367, decDegrees: 31.7167, magnitude: 7.0),
        DeepSkyObject(catalog: .caldwell, number: 34, name: "Western Veil Nebula", type: .supernovaRemnant, constellation: "Cyg", raHours: 20.7600, decDegrees: 30.7167, magnitude: 7.0),
        DeepSkyObject(catalog: .caldwell, number: 35, name: nil, type: .galaxy, constellation: "Com", raHours: 12.9822, decDegrees: 28.2544, magnitude: 11.4),
        DeepSkyObject(catalog: .caldwell, number: 36, name: nil, type: .galaxy, constellation: "Com", raHours: 12.5906, decDegrees: 27.9597, magnitude: 10.1),
        DeepSkyObject(catalog: .caldwell, number: 37, name: nil, type: .openCluster, constellation: "Vul", raHours: 20.1817, decDegrees: 26.4833, magnitude: 6.9),
        DeepSkyObject(catalog: .caldwell, number: 38, name: "Needle Galaxy", type: .galaxy, constellation: "Com", raHours: 12.6108, decDegrees: 25.9908, magnitude: 9.6),
        DeepSkyObject(catalog: .caldwell, number: 39, name: "Eskimo Nebula", type: .planetaryNebula, constellation: "Gem", raHours: 7.4894, decDegrees: 20.9117, magnitude: 9.2),
        DeepSkyObject(catalog: .caldwell, number: 40, name: nil, type: .galaxy, constellation: "Leo", raHours: 11.3358, decDegrees: 18.3547, magnitude: 11.4),
        DeepSkyObject(catalog: .caldwell, number: 41, name: "Hyades", type: .openCluster, constellation: "Tau", raHours: 4.4500, decDegrees: 15.8667, magnitude: 0.5),
        DeepSkyObject(catalog: .caldwell, number: 42, name: nil, type: .globularCluster, constellation: "Del", raHours: 21.0117, decDegrees: 16.1839, magnitude: 8.9),
        DeepSkyObject(catalog: .caldwell, number: 43, name: nil, type: .galaxy, constellation: "Peg", raHours: 23.0511, decDegrees: 14.4406, magnitude: 10.2),
        DeepSkyObject(catalog: .caldwell, number: 44, name: nil, type: .galaxy, constellation: "Peg", raHours: 23.0400, decDegrees: 12.3231, magnitude: 10.4),
        DeepSkyObject(catalog: .caldwell, number: 45, name: nil, type: .galaxy, constellation: "Boo", raHours: 15.2544, decDegrees: 5.3350, magnitude: 10.0),
        DeepSkyObject(catalog: .caldwell, number: 46, name: "Hubble's Variable Nebula", type: .nebula, constellation: "Mon", raHours: 6.6544, decDegrees: 8.7333, magnitude: 9.0),
        DeepSkyObject(catalog: .caldwell, number: 47, name: nil, type: .globularCluster, constellation: "Del", raHours: 20.5344, decDegrees: 7.4044, magnitude: 8.9),
        DeepSkyObject(catalog: .caldwell, number: 48, name: nil, type: .galaxy, constellation: "Cnc", raHours: 8.2072, decDegrees: 21.4933, magnitude: 10.3),
        DeepSkyObject(catalog: .caldwell, number: 49, name: "Rosette Nebula", type: .nebula, constellation: "Mon", raHours: 6.5389, decDegrees: 4.9500, magnitude: 5.5),
        DeepSkyObject(catalog: .caldwell, number: 50, name: nil, type: .openCluster, constellation: "Mon", raHours: 6.5333, decDegrees: 4.9333, magnitude: 4.8),
        DeepSkyObject(catalog: .caldwell, number: 51, name: nil, type: .galaxy, constellation: "Cet", raHours: 0.3358, decDegrees: -0.0244, magnitude: 9.8),
        DeepSkyObject(catalog: .caldwell, number: 52, name: nil, type: .galaxy, constellation: "Vir", raHours: 12.6683, decDegrees: -0.0225, magnitude: 9.5),
        DeepSkyObject(catalog: .caldwell, number: 53, name: "Spindle Galaxy", type: .galaxy, constellation: "Sex", raHours: 10.0975, decDegrees: -7.7200, magnitude: 9.1),
        DeepSkyObject(catalog: .caldwell, number: 54, name: nil, type: .openCluster, constellation: "Mon", raHours: 8.0000, decDegrees: -10.7833, magnitude: 7.6),
        DeepSkyObject(catalog: .caldwell, number: 55, name: "Saturn Nebula", type: .planetaryNebula, constellation: "Aqr", raHours: 21.0672, decDegrees: -11.3672, magnitude: 8.0),
        DeepSkyObject(catalog: .caldwell, number: 56, name: nil, type: .planetaryNebula, constellation: "Cet", raHours: 1.7392, decDegrees: -11.8722, magnitude: 10.9),
        DeepSkyObject(catalog: .caldwell, number: 57, name: "Barnard's Galaxy", type: .galaxy, constellation: "Sgr", raHours: 19.7500, decDegrees: -14.8067, magnitude: 9.3),
        DeepSkyObject(catalog: .caldwell, number: 58, name: nil, type: .openCluster, constellation: "CMa", raHours: 7.2450, decDegrees: -15.6167, magnitude: 7.2),
        DeepSkyObject(catalog: .caldwell, number: 59, name: "Ghost of Jupiter", type: .planetaryNebula, constellation: "Hya", raHours: 10.4483, decDegrees: -18.6383, magnitude: 7.8),
        DeepSkyObject(catalog: .caldwell, number: 60, name: "Antennae Galaxies", type: .galaxy, constellation: "Crv", raHours: 12.0294, decDegrees: -18.8683, magnitude: 10.7),
        DeepSkyObject(catalog: .caldwell, number: 61, name: "Antennae Galaxies", type: .galaxy, constellation: "Crv", raHours: 12.0297, decDegrees: -18.8792, magnitude: 11.1),
        DeepSkyObject(catalog: .caldwell, number: 62, name: nil, type: .galaxy, constellation: "Cet", raHours: 0.7581, decDegrees: -20.7592, magnitude: 9.5),
        DeepSkyObject(catalog: .caldwell, number: 63, name: "Helix Nebula", type: .planetaryNebula, constellation: "Aqr", raHours: 22.4939, decDegrees: -20.8372, magnitude: 7.3),
        DeepSkyObject(catalog: .caldwell, number: 64, name: nil, type: .openCluster, constellation: "CMa", raHours: 7.3050, decDegrees: -24.1667, magnitude: 4.1),
        DeepSkyObject(catalog: .caldwell, number: 65, name: "Sculptor Galaxy", type: .galaxy, constellation: "Scl", raHours: 0.7906, decDegrees: -25.2883, magnitude: 7.1),
        DeepSkyObject(catalog: .caldwell, number: 66, name: nil, type: .globularCluster, constellation: "Hya", raHours: 14.0658, decDegrees: -26.5406, magnitude: 7.6),
        DeepSkyObject(catalog: .caldwell, number: 67, name: nil, type: .galaxy, constellation: "For", raHours: 3.5567, decDegrees: -25.5622, magnitude: 9.9),
        DeepSkyObject(catalog: .caldwell, number: 68, name: nil, type: .nebula, constellation: "CrA", raHours: 18.9683, decDegrees: -36.9567, magnitude: 9.7),
        DeepSkyObject(catalog: .caldwell, number: 69, name: "Bug Nebula", type: .planetaryNebula, constellation: "Sco", raHours: 17.2244, decDegrees: -37.1031, magnitude: 12.8),
        DeepSkyObject(catalog: .caldwell, number: 70, name: nil, type: .galaxy, constellation: "Scl", raHours: 0.9147, decDegrees: -37.6858, magnitude: 8.1),
        DeepSkyObject(catalog: .caldwell, number: 71, name: nil, type: .openCluster, constellation: "Pup", raHours: 7.8617, decDegrees: -38.5333, magnitude: 5.8),
        DeepSkyObject(catalog: .caldwell, number: 72, name: nil, type: .galaxy, constellation: "Scl", raHours: 0.2456, decDegrees: -39.1969, magnitude: 8.4),
        DeepSkyObject(catalog: .caldwell, number: 73, name: nil, type: .globularCluster, constellation: "Col", raHours: 5.2214, decDegrees: -40.0464, magnitude: 7.3),
        DeepSkyObject(catalog: .caldwell, number: 74, name: "Eight-Burst Nebula", type: .planetaryNebula, constellation: "Vel", raHours: 10.1275, decDegrees: -40.4361, magnitude: 8.2),
        DeepSkyObject(catalog: .caldwell, number: 75, name: nil, type: .openCluster, constellation: "Sco", raHours: 16.2550, decDegrees: -40.6667, magnitude: 5.8),
        DeepSkyObject(catalog: .caldwell, number: 76, name: nil, type: .openCluster, constellation: "Sco", raHours: 16.8933, decDegrees: -41.8167, magnitude: 2.6),
        DeepSkyObject(catalog: .caldwell, number: 77, name: "Centaurus A", type: .galaxy, constellation: "Cen", raHours: 13.4247, decDegrees: -43.0192, magnitude: 6.8),
        DeepSkyObject(catalog: .caldwell, number: 78, name: nil, type: .globularCluster, constellation: "CrA", raHours: 18.1069, decDegrees: -42.7367, magnitude: 6.6),
        DeepSkyObject(catalog: .caldwell, number: 79, name: nil, type: .globularCluster, constellation: "Vel", raHours: 10.2894, decDegrees: -46.4108, magnitude: 6.7),
        DeepSkyObject(catalog: .caldwell, number: 80, name: "Omega Centauri", type: .globularCluster, constellation: "Cen", raHours: 13.4461, decDegrees: -47.4769, magnitude: 3.7),
        DeepSkyObject(catalog: .caldwell, number: 81, name: nil, type: .globularCluster, constellation: "Ara", raHours: 17.3103, decDegrees: -48.4239, magnitude: 8.1),
        DeepSkyObject(catalog: .caldwell, number: 82, name: nil, type: .openCluster, constellation: "Ara", raHours: 16.6767, decDegrees: -48.7667, magnitude: 5.2),
        DeepSkyObject(catalog: .caldwell, number: 83, name: nil, type: .galaxy, constellation: "Cen", raHours: 13.2172, decDegrees: -49.4675, magnitude: 9.5),
        DeepSkyObject(catalog: .caldwell, number: 84, name: nil, type: .globularCluster, constellation: "Cen", raHours: 13.7739, decDegrees: -51.3775, magnitude: 7.6),
        DeepSkyObject(catalog: .caldwell, number: 85, name: nil, type: .openCluster, constellation: "Vel", raHours: 8.7333, decDegrees: -53.0667, magnitude: 2.5),
        DeepSkyObject(catalog: .caldwell, number: 86, name: nil, type: .globularCluster, constellation: "Ara", raHours: 17.6772, decDegrees: -53.6739, magnitude: 5.6),
        DeepSkyObject(catalog: .caldwell, number: 87, name: nil, type: .globularCluster, constellation: "Hor", raHours: 3.2039, decDegrees: -55.2158, magnitude: 8.4),
        DeepSkyObject(catalog: .caldwell, number: 88, name: nil, type: .openCluster, constellation: "Cir", raHours: 15.3050, decDegrees: -60.9833, magnitude: 7.9),
        DeepSkyObject(catalog: .caldwell, number: 89, name: nil, type: .openCluster, constellation: "Nor", raHours: 16.2517, decDegrees: -57.9000, magnitude: 5.4),
        DeepSkyObject(catalog: .caldwell, number: 90, name: nil, type: .planetaryNebula, constellation: "Car", raHours: 10.7433, decDegrees: -58.0000, magnitude: 9.7),
        DeepSkyObject(catalog: .caldwell, number: 91, name: nil, type: .openCluster, constellation: "Car", raHours: 11.0583, decDegrees: -58.6333, magnitude: 3.0),
        DeepSkyObject(catalog: .caldwell, number: 92, name: "Eta Carinae Nebula", type: .nebula, constellation: "Car", raHours: 10.7375, decDegrees: -59.8667, magnitude: 3.0),
        DeepSkyObject(catalog: .caldwell, number: 93, name: nil, type: .globularCluster, constellation: "Pav", raHours: 19.1786, decDegrees: -59.9847, magnitude: 5.4),
        DeepSkyObject(catalog: .caldwell, number: 94, name: "Jewel Box", type: .openCluster, constellation: "Cru", raHours: 12.8967, decDegrees: -60.3500, magnitude: 4.2),
        DeepSkyObject(catalog: .caldwell, number: 95, name: nil, type: .openCluster, constellation: "TrA", raHours: 16.2867, decDegrees: -60.7500, magnitude: 5.1),
        DeepSkyObject(catalog: .caldwell, number: 96, name: nil, type: .openCluster, constellation: "Car", raHours: 7.9450, decDegrees: -60.8667, magnitude: 3.8),
        DeepSkyObject(catalog: .caldwell, number: 97, name: nil, type: .openCluster, constellation: "Cen", raHours: 11.9367, decDegrees: -61.6167, magnitude: 5.3),
        DeepSkyObject(catalog: .caldwell, number: 98, name: nil, type: .openCluster, constellation: "Cru", raHours: 12.8867, decDegrees: -63.3000, magnitude: 6.9),
        DeepSkyObject(catalog: .caldwell, number: 99, name: "Coalsack", type: .nebula, constellation: "Cru", raHours: 12.8833, decDegrees: -63.0000, magnitude: 5.0),
        DeepSkyObject(catalog: .caldwell, number: 100, name: nil, type: .openCluster, constellation: "Cen", raHours: 11.6100, decDegrees: -63.3000, magnitude: 4.5),
        DeepSkyObject(catalog: .caldwell, number: 101, name: nil, type: .galaxy, constellation: "Pav", raHours: 20.1214, decDegrees: -66.1794, magnitude: 9.0),
        DeepSkyObject(catalog: .caldwell, number: 102, name: "Southern Pleiades", type: .openCluster, constellation: "Car", raHours: 10.7150, decDegrees: -64.4000, magnitude: 1.9),
        DeepSkyObject(catalog: .caldwell, number: 103, name: "Tarantula Nebula", type: .nebula, constellation: "Dor", raHours: 5.6431, decDegrees: -69.0983, magnitude: 8.2),
        DeepSkyObject(catalog: .caldwell, number: 104, name: nil, type: .globularCluster, constellation: "Tuc", raHours: 1.0511, decDegrees: -70.8481, magnitude: 6.6),
        DeepSkyObject(catalog: .caldwell, number: 105, name: nil, type: .galaxy, constellation: "Mus", raHours: 13.2222, decDegrees: -68.7139, magnitude: 11.0),
        DeepSkyObject(catalog: .caldwell, number: 106, name: "47 Tucanae", type: .globularCluster, constellation: "Tuc", raHours: 0.4014, decDegrees: -72.0814, magnitude: 4.0),
        DeepSkyObject(catalog: .caldwell, number: 107, name: nil, type: .globularCluster, constellation: "Aps", raHours: 16.5389, decDegrees: -70.8483, magnitude: 9.3),
        DeepSkyObject(catalog: .caldwell, number: 108, name: nil, type: .globularCluster, constellation: "Mus", raHours: 12.4222, decDegrees: -70.8781, magnitude: 7.8),
        DeepSkyObject(catalog: .caldwell, number: 109, name: nil, type: .planetaryNebula, constellation: "Cha", raHours: 10.1783, decDegrees: -80.8703, magnitude: 11.6),
    ]
}
