import Foundation

enum NGCHighlights {
    static let objects: [DeepSkyObject] = [
        DeepSkyObject(catalog: .ngc, number: 55, name: nil, type: .galaxy, constellation: "Scl", raHours: 0.250, decDegrees: -39.196, magnitude: 8.4),
        DeepSkyObject(catalog: .ngc, number: 253, name: "Sculptor Galaxy", type: .galaxy, constellation: "Scl", raHours: 0.792, decDegrees: -25.288, magnitude: 7.2),
        DeepSkyObject(catalog: .ngc, number: 300, name: nil, type: .galaxy, constellation: "Scl", raHours: 0.915, decDegrees: -37.685, magnitude: 8.1),
        DeepSkyObject(catalog: .ngc, number: 457, name: "Owl Cluster", type: .openCluster, constellation: "Cas", raHours: 1.317, decDegrees: 58.283, magnitude: 6.4),
        DeepSkyObject(catalog: .ngc, number: 663, name: nil, type: .openCluster, constellation: "Cas", raHours: 1.767, decDegrees: 61.217, magnitude: 7.1),
        DeepSkyObject(catalog: .ngc, number: 752, name: nil, type: .openCluster, constellation: "And", raHours: 1.965, decDegrees: 37.683, magnitude: 5.7),
        DeepSkyObject(catalog: .ngc, number: 869, name: "Double Cluster (h Per)", type: .openCluster, constellation: "Per", raHours: 2.317, decDegrees: 57.133, magnitude: 5.3),
        DeepSkyObject(catalog: .ngc, number: 884, name: "Double Cluster (chi Per)", type: .openCluster, constellation: "Per", raHours: 2.367, decDegrees: 57.133, magnitude: 6.1),
        DeepSkyObject(catalog: .ngc, number: 891, name: nil, type: .galaxy, constellation: "And", raHours: 2.375, decDegrees: 42.349, magnitude: 9.9),
        DeepSkyObject(catalog: .ngc, number: 1097, name: nil, type: .galaxy, constellation: "For", raHours: 2.772, decDegrees: -30.275, magnitude: 9.5),
        DeepSkyObject(catalog: .ngc, number: 1232, name: nil, type: .galaxy, constellation: "Eri", raHours: 3.164, decDegrees: -20.579, magnitude: 9.9),
        DeepSkyObject(catalog: .ngc, number: 1300, name: nil, type: .galaxy, constellation: "Eri", raHours: 3.331, decDegrees: -19.411, magnitude: 10.4),
        DeepSkyObject(catalog: .ngc, number: 1332, name: nil, type: .galaxy, constellation: "Eri", raHours: 3.438, decDegrees: -21.335, magnitude: 10.3),
        DeepSkyObject(catalog: .ngc, number: 1365, name: nil, type: .galaxy, constellation: "For", raHours: 3.560, decDegrees: -36.140, magnitude: 9.6),
        DeepSkyObject(catalog: .ngc, number: 1499, name: "California Nebula", type: .nebula, constellation: "Per", raHours: 4.006, decDegrees: 36.417, magnitude: 5.0),
        DeepSkyObject(catalog: .ngc, number: 2244, name: nil, type: .openCluster, constellation: "Mon", raHours: 6.533, decDegrees: 4.867, magnitude: 4.8),
        DeepSkyObject(catalog: .ngc, number: 2264, name: "Christmas Tree Cluster", type: .openCluster, constellation: "Mon", raHours: 6.683, decDegrees: 9.883, magnitude: 3.9),
        DeepSkyObject(catalog: .ngc, number: 2359, name: "Thor's Helmet", type: .nebula, constellation: "CMa", raHours: 7.302, decDegrees: -13.203, magnitude: 11.5),
        DeepSkyObject(catalog: .ngc, number: 2403, name: nil, type: .galaxy, constellation: "Cam", raHours: 7.618, decDegrees: 65.603, magnitude: 8.9),
        DeepSkyObject(catalog: .ngc, number: 2419, name: "Intergalactic Wanderer", type: .globularCluster, constellation: "Lyn", raHours: 7.653, decDegrees: 38.883, magnitude: 9.1),
        DeepSkyObject(catalog: .ngc, number: 2903, name: nil, type: .galaxy, constellation: "Leo", raHours: 9.533, decDegrees: 21.500, magnitude: 9.0),
        DeepSkyObject(catalog: .ngc, number: 3115, name: "Spindle Galaxy", type: .galaxy, constellation: "Sex", raHours: 10.088, decDegrees: -7.719, magnitude: 8.9),
        DeepSkyObject(catalog: .ngc, number: 3521, name: nil, type: .galaxy, constellation: "Leo", raHours: 11.096, decDegrees: -0.036, magnitude: 9.0),
        DeepSkyObject(catalog: .ngc, number: 3628, name: "Hamburger Galaxy", type: .galaxy, constellation: "Leo", raHours: 11.335, decDegrees: 13.590, magnitude: 9.5),
        DeepSkyObject(catalog: .ngc, number: 4038, name: "Antennae Galaxies", type: .galaxy, constellation: "Crv", raHours: 12.030, decDegrees: -18.867, magnitude: 10.3),
        DeepSkyObject(catalog: .ngc, number: 4565, name: "Needle Galaxy", type: .galaxy, constellation: "Com", raHours: 12.606, decDegrees: 25.988, magnitude: 9.6),
        DeepSkyObject(catalog: .ngc, number: 4631, name: "Whale Galaxy", type: .galaxy, constellation: "CVn", raHours: 12.703, decDegrees: 32.542, magnitude: 9.2),
        DeepSkyObject(catalog: .ngc, number: 4656, name: "Hockey Stick Galaxy", type: .galaxy, constellation: "CVn", raHours: 12.720, decDegrees: 32.170, magnitude: 10.5),
        DeepSkyObject(catalog: .ngc, number: 5033, name: nil, type: .galaxy, constellation: "CVn", raHours: 13.219, decDegrees: 36.594, magnitude: 10.1),
        DeepSkyObject(catalog: .ngc, number: 5866, name: "Spindle Galaxy", type: .galaxy, constellation: "Dra", raHours: 15.108, decDegrees: 55.763, magnitude: 9.9),
        DeepSkyObject(catalog: .ngc, number: 6231, name: nil, type: .openCluster, constellation: "Sco", raHours: 16.905, decDegrees: -41.833, magnitude: 2.6),
        DeepSkyObject(catalog: .ngc, number: 6334, name: "Cat's Paw Nebula", type: .nebula, constellation: "Sco", raHours: 17.335, decDegrees: -35.783, magnitude: 5.0),
        DeepSkyObject(catalog: .ngc, number: 6357, name: "Lobster Nebula", type: .nebula, constellation: "Sco", raHours: 17.412, decDegrees: -34.200, magnitude: 6.4),
        DeepSkyObject(catalog: .ngc, number: 6822, name: "Barnard's Galaxy", type: .galaxy, constellation: "Sgr", raHours: 19.752, decDegrees: -14.803, magnitude: 8.7),
        DeepSkyObject(catalog: .ngc, number: 6934, name: nil, type: .globularCluster, constellation: "Del", raHours: 20.575, decDegrees: 7.404, magnitude: 8.8),
        DeepSkyObject(catalog: .ngc, number: 7000, name: "North America Nebula", type: .nebula, constellation: "Cyg", raHours: 20.983, decDegrees: 44.517, magnitude: 4.0),
        DeepSkyObject(catalog: .ngc, number: 7009, name: "Saturn Nebula", type: .planetaryNebula, constellation: "Aqr", raHours: 21.070, decDegrees: -11.363, magnitude: 8.0),
        DeepSkyObject(catalog: .ngc, number: 7331, name: nil, type: .galaxy, constellation: "Peg", raHours: 22.617, decDegrees: 34.416, magnitude: 9.5),
        DeepSkyObject(catalog: .ngc, number: 7479, name: nil, type: .galaxy, constellation: "Peg", raHours: 23.083, decDegrees: 12.323, magnitude: 10.9),
        DeepSkyObject(catalog: .ngc, number: 7793, name: nil, type: .galaxy, constellation: "Scl", raHours: 23.963, decDegrees: -32.591, magnitude: 9.1),
    ]
}
